### ISSUE TITLE
The phone does not charge in Windows 10. Телефон не заряжается в Windows 10.

### ISSUE THREAD

**Issue by Hemp007** [gus33000/MSM8994-8992-NT-ARM64-Drivers#16] opened 2019-05-29 13:52 UTC
The phone does not charge in Windows 10. What could be the reason?

Телефон не заряжается в Windows 10. В чем может быть причина?

**Comment by woachk** [comment] 2019-05-31 13:07
Does it charge with the screen off under Connected Standby? Which Woa Deployer version did you use?

**Comment by Hemp007** [comment] 2019-06-01 01:01
Yes, in the off state there is a charge, but then the phone turns on automatically and the OS does not charge. I used the assembled FFU image and installation via the command line.

**Comment by feherneoh** [comment] 2019-06-01 08:36
> Yes, in the off state there is a charge, but then the phone turns on automatically and the OS does not charge. I used the assembled FFU image and installation via the command line.

That wasn't the question.
It wasn't about the phone, but the display being turned off (so basically the phone locked)

**Comment by Hemp007** [comment] 2019-06-01 14:10
> > Yes, in the off state there is a charge, but then the phone turns on automatically and the OS does not charge. I used the assembled FFU image and installation via the command line.
> 
> That wasn't the question.
> It wasn't about the phone, but the display being turned off (so basically the phone locked)

No, with a locked screen, the charge does not go, there is no charge indicator.

**Comment by feherneoh** [comment] 2019-06-01 19:05
> > > Yes, in the off state there is a charge, but then the phone turns on automatically and the OS does not charge. I used the assembled FFU image and installation via the command line.
> > 
> > 
> > That wasn't the question.
> > It wasn't about the phone, but the display being turned off (so basically the phone locked)
> 
> No, with a locked screen, the charge does not go, there is no charge indicator.

if you turn the display off, you cannot see if there is an indicator or not

the indicator usually takes about 2 minutes to appear if it appeares at all, but the phone should still charge while the display is off, even if there is no indication of it

if it doesn't, then the problem is probably with the specific charger you are using
Lumia 950XL stock charger usually works, Xiaomi/Asus 2A chargers seem to work even while the screen is on (using the stock C cable)

**Comment by Hemp007** [comment] 2019-06-02 08:54
The cable is working, the charge is only for wireless charging.
The indicator meant in the tray, it is not from the cable, there is a wireless charging.
Yesterday I reinstalled via WOA Deployer, nothing has changed.

**Comment by gus33000** [comment] 2019-06-15 13:44
Possible consequence of #28 
Charging using a PC usb port most likely works in your case

**Comment by gus33000** [comment] 2019-08-28 10:29
Issue fixed in 1909 (Should be released next week)

**Closed as completed by gus33000** 2019-08-28 10:29 UTC
Labels: Power
