### ISSUE TITLE
screen reverse

### ISSUE THREAD

**Issue by AlvinLIQ** [gus33000/MSM8994-8992-NT-ARM64-Drivers#46] opened 2019-08-27 03:15 UTC
[problem]
My display and touch are reversed with this new auto roate driver and it still cannot rotate automatically.
[machine]
lumia 950 (RM_1104)

**Comment by gus33000** [comment] 2019-08-28 10:23
Closing issue as it relates to prerelease software being tested only in a specific group with select people. Please report issues about prerelease versions in that prerelease testing group.

Issue might also been fixed since with recent commits.

**Closed as completed by gus33000** 2019-08-28 10:23 UTC

**Comment by gus33000** [comment] 2019-08-28 10:25
Screen being flipped might also been caused by incorrect installation of the driver pack. You can report to our wiki for manual installation instructions, as we flip the display and touch on Acer jade Primo devices only.

Edit: relevant link: https://github.com/WOA-Project/MSM8994-8992-NT-ARM64-Drivers/wiki/Installing-drivers-manually
